/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSearchRouteImport } from './routes/app/search'
import { Route as AppRiskRouteImport } from './routes/app/risk'
import { Route as AppReportsRouteImport } from './routes/app/reports'
import { Route as AppProcurementRouteImport } from './routes/app/procurement'
import { Route as AppPricesRouteImport } from './routes/app/prices'
import { Route as AppNewsRouteImport } from './routes/app/news'
import { Route as AppMarketRouteImport } from './routes/app/market'
import { Route as AppMapRouteImport } from './routes/app/map'
import { Route as AppDiscoveryRouteImport } from './routes/app/discovery'
import { Route as AppCompareRouteImport } from './routes/app/compare'
import { Route as AppCompaniesRouteImport } from './routes/app/companies'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as AppAdminRouteImport } from './routes/app/admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementRoute = AppProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => AppRoute,
} as any)
const AppPricesRoute = AppPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsRoute = AppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoveryRoute = AppDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/chat': typeof AppChatRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/compare': typeof AppCompareRoute
  '/app/discovery': typeof AppDiscoveryRoute
  '/app/map': typeof AppMapRoute
  '/app/market': typeof AppMarketRoute
  '/app/news': typeof AppNewsRoute
  '/app/prices': typeof AppPricesRoute
  '/app/procurement': typeof AppProcurementRoute
  '/app/reports': typeof AppReportsRoute
  '/app/risk': typeof AppRiskRoute
  '/app/search': typeof AppSearchRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/chat': typeof AppChatRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/compare': typeof AppCompareRoute
  '/app/discovery': typeof AppDiscoveryRoute
  '/app/map': typeof AppMapRoute
  '/app/market': typeof AppMarketRoute
  '/app/news': typeof AppNewsRoute
  '/app/prices': typeof AppPricesRoute
  '/app/procurement': typeof AppProcurementRoute
  '/app/reports': typeof AppReportsRoute
  '/app/risk': typeof AppRiskRoute
  '/app/search': typeof AppSearchRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/chat': typeof AppChatRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/compare': typeof AppCompareRoute
  '/app/discovery': typeof AppDiscoveryRoute
  '/app/map': typeof AppMapRoute
  '/app/market': typeof AppMarketRoute
  '/app/news': typeof AppNewsRoute
  '/app/prices': typeof AppPricesRoute
  '/app/procurement': typeof AppProcurementRoute
  '/app/reports': typeof AppReportsRoute
  '/app/risk': typeof AppRiskRoute
  '/app/search': typeof AppSearchRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/analytics'
    | '/app/chat'
    | '/app/companies'
    | '/app/compare'
    | '/app/discovery'
    | '/app/map'
    | '/app/market'
    | '/app/news'
    | '/app/prices'
    | '/app/procurement'
    | '/app/reports'
    | '/app/risk'
    | '/app/search'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/admin'
    | '/app/analytics'
    | '/app/chat'
    | '/app/companies'
    | '/app/compare'
    | '/app/discovery'
    | '/app/map'
    | '/app/market'
    | '/app/news'
    | '/app/prices'
    | '/app/procurement'
    | '/app/reports'
    | '/app/risk'
    | '/app/search'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/analytics'
    | '/app/chat'
    | '/app/companies'
    | '/app/compare'
    | '/app/discovery'
    | '/app/map'
    | '/app/market'
    | '/app/news'
    | '/app/prices'
    | '/app/procurement'
    | '/app/reports'
    | '/app/risk'
    | '/app/search'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risk': {
      id: '/app/risk'
      path: '/risk'
      fullPath: '/app/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/procurement': {
      id: '/app/procurement'
      path: '/procurement'
      fullPath: '/app/procurement'
      preLoaderRoute: typeof AppProcurementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prices': {
      id: '/app/prices'
      path: '/prices'
      fullPath: '/app/prices'
      preLoaderRoute: typeof AppPricesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/news': {
      id: '/app/news'
      path: '/news'
      fullPath: '/app/news'
      preLoaderRoute: typeof AppNewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market': {
      id: '/app/market'
      path: '/market'
      fullPath: '/app/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discovery': {
      id: '/app/discovery'
      path: '/discovery'
      fullPath: '/app/discovery'
      preLoaderRoute: typeof AppDiscoveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compare': {
      id: '/app/compare'
      path: '/compare'
      fullPath: '/app/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/companies': {
      id: '/app/companies'
      path: '/companies'
      fullPath: '/app/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppChatRoute: typeof AppChatRoute
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppCompareRoute: typeof AppCompareRoute
  AppDiscoveryRoute: typeof AppDiscoveryRoute
  AppMapRoute: typeof AppMapRoute
  AppMarketRoute: typeof AppMarketRoute
  AppNewsRoute: typeof AppNewsRoute
  AppPricesRoute: typeof AppPricesRoute
  AppProcurementRoute: typeof AppProcurementRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRiskRoute: typeof AppRiskRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppChatRoute: AppChatRoute,
  AppCompaniesRoute: AppCompaniesRoute,
  AppCompareRoute: AppCompareRoute,
  AppDiscoveryRoute: AppDiscoveryRoute,
  AppMapRoute: AppMapRoute,
  AppMarketRoute: AppMarketRoute,
  AppNewsRoute: AppNewsRoute,
  AppPricesRoute: AppPricesRoute,
  AppProcurementRoute: AppProcurementRoute,
  AppReportsRoute: AppReportsRoute,
  AppRiskRoute: AppRiskRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
